package.json

Added missing babel dependencies to the package.json

Added babel dependencies

---

src/control/cad.js
src/control/delete.js
src/control/draw.js
src/control/modify.js
src/control/move.js
src/control/rotate.js

Allow overriding default control options.

---

package.json

Preperation for NPM release, to close #9. Anything else?

NPM release

---

.travis.yml

Added travis instruction according to https://github.com/greenkeeperio/greenkeeper-lockfile#setup

Made greenkeeper-lockfile aware of the yarn.lock file

---

.travis.yml
package-lock.json

Added package-lock.json as mentioned in #18

Added npm@5 and package-lock.json for greenkeeper

---

index.html
style/style.css

'Join the team!' ribbon is not rendered well for different screen size.

demo page - ribbon css adaptation

---

src/control/rotate.js

Fix for issue https://github.com/geops/ole2/issues/34.

Allow Pan and Zoom when Rotate Control is enabled

---

.neutrinorc.js
index.html
package.json
src/control/buffer.js
src/control/cad.js
src/control/control.js
src/control/delete.js
src/control/draw.js
src/control/modify.js
src/control/move.js
src/control/rotate.js
src/control/topology.js
src/editor.js
src/index.html
src/index.js
src/service/index.js
src/service/local-storage.js
src/service/localStorage.js
src/service/service.js
src/service/storage.js

* Introducing ole.Service
* Added a generic ole.service.Storage. 
* Implemented ole.service.LocalStorage for saving control properties in the localStorage.

Storing control properties.

---

package.json

chore(package): update cypress to version 3.0.1

---

.neutrinorc.js
index.html
package.json
src/control/buffer.js
src/control/cad.js
src/control/control.js
src/control/delete.js
src/control/difference.js
src/control/draw.js
src/control/intersection.js
src/control/modify.js
src/control/move.js
src/control/rotate.js
src/control/topology.js
src/control/union.js
src/editor.js
src/index.html
src/toolbar.js

This jsut to keep the work somewhere ingeops repo. In case we need it in the future.

Use es 6 import for jsts and ol .

---

.gitignore
index.html
package.json
src/control/buffer.js
src/control/cad.js
src/control/control.js
src/control/delete.js
src/control/draw.js
src/control/modify.js
src/control/rotate.js
src/control/topology.js
src/index.html
src/toolbar.js

Update to use last version of  ol 5 and jsts 2.

Update jsts and ol

---

CHANGELOG.md
package.json
src/control/control.js

Sorry I failed the deploy of 0.0.2

Build before packing

---

index.html
src/control/buffer.js
src/control/cad.js
src/control/control.js
src/control/delete.js
src/control/draw.js
src/control/modify.js
src/control/move.js
src/control/rotate.js
src/control/topology.js
src/index.html
src/toolbar.js

- update documentation of parameters for some controls
- Replace `source` property by `layers` property for Select interaction
- Apply the select style on top of the feature's style.
- Prettify the html

Update documentation and fix use of Select interaction :)

---

src/index.html

https://lgtm.com/projects/g/geops/openlayers-editor/snapshot/f5b8c03b2f4a22584fb51b4c9283596b140eaa1e/files/src/index.html?sort=name&dir=ASC&mode=heatmap#xc053677fdab14e8d:1

Avoid automated semicolin insertion

---

src/service/storage.js

https://lgtm.com/projects/g/geops/openlayers-editor/snapshot/f5b8c03b2f4a22584fb51b4c9283596b140eaa1e/files/src/service/storage.js?sort=name&dir=ASC&mode=heatmap#x7a9a5798f5db9b54:1

Removed superfluous argument passed to constructor

---

src/control/modify.js
src/index.html

Defined a default style for modifying geometries

Default select style

---

src/control/modify.js

implemented custom and default hit tolerance for clicks on the select and modify interactions

Click radius increase for select move and modify

---

index.html
src/control/modify.js
src/index.html

updated api documentation, added wrapX:false to all layers

Documentation update and wrapX bugfix

---

package.json
src/control/control.js
src/control/modify.js

and use layerFilter to avoid https://github.com/openlayers/openlayers/issues/6646

Fix css of cursor

---

src/control/modify.js

event listener listening to keyCode = 46 instead of key = 'Delete'

Delete feature event with keyCode

---

src/control/cad.js
src/index.html

* Added parameter to CAD tool
* Takes a function with the source as a single argument
* Returns and array of features
* Can be used to limit/specify the features to snap to

Added CAD configurability

---

src/control/modify.js

* Implemented toggleCondition for Move and Modify Selection as class option
* needed for Plan-Editor to select multiple features using the shift key

Configurable ToggleCondition for Move/Modify

---

.github/stale.yml

Added configuration for automatic stale issue closing

Added stale bot configuration

---

package.json

Update webpack according to greenkeeper.
Last action before greenkeeper disable

chore(package): update webpack to version 4.41.3

---

README.md

docs: lint readme.md

---

src/control/cad.js

fix(cad): allow a snap distance of 0

---

index.html

Update style URL on demo page

---

index.html
package.json
src/control/draw.js

Adds the possibility to configure the ol Draw interaction's options by passing it in through the options of the DrawControl

fix(DrawControl): add drawInteractionOptions for DrawControl

---

.github/workflows/test.yml

chore: use yarn in test gh-action

---

.github/workflows/test.yml

chore: fix test gh-action

---

.github/workflows/cypress.yml
api.html
index.html
style/style.css

fix: add privacy, imprint and about links, improve header links layout

---

src/control/buffer.js
src/control/cad.js
src/control/difference.js
src/control/draw.js
src/control/intersection.js
src/control/modify.js
src/control/rotate.js
src/control/topology.js
src/control/union.js

Update some JSDoc comments to improve TypScript definitions.

fix: update JSDoc comments to improve TypeScript definitions

---

src/control/cad.js

This MR is simply adjusting the properties made available on the cad control to match it's current contract

docs: Updating cad control options to match current props
